import "~/styles/globals.css";
import { TRPCReactProvider } from "~/trpc/react";
import { Inter } from "next/font/google";
import Navbar from "./_components/navbar";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} dark`}>
      <body>
        <TRPCReactProvider>
          <Navbar/>
          {children}
          </TRPCReactProvider>
      </body>
    </html>
  );
}
